dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: UT0Cl3WoDQLSGdgPvLNbDfZaksvRQRGGl8SiyL0HqX8bz4lff/xxE2wIvtOqok4EHMqppOKY630kjbWo/rAkEXVDTAZ9c90oBmyWk6hwBsfAWKh+dQSkIhn/wsLE+qsaldU6/oV3sS9U65EJM+di7S3SYoapGMKg1n7TufHgbfTeUpPi8VMRzW/uKUxDRzQVBkJS3fh87CIrRsNGwT5gw+RN4x+zeXm2yIw4sPLVkUe4Yrup69FB6I78zyLoDmX219rAkkVmLdwcZc3ocLP7RFmJJUGu2yb8lsYChnQN3Sk5B88Uekbt2Qr07XX5AOuciDCGt9XlbU/PvB3z2k0DaWcBkQ+8MtDi9CiPeN/oXNyTpW4wENzgsGGUCmJ1F0kLPmtisHsG7QbSOXU9bcvqZjezDoGqRSWpzzHFq6nyRm/I0LNiPKJhOdhxdk/X6LiwCokVReGePZYGvKEoWsnjPge5ekeTUfOiDGaFcxTerlokZ3Mxqwr4kX8Nh2U13Kql8irN9Dep11KnwOQNO0e1vZOvEx4yrtuC7wQIgPzo0VIJVzVoUiLG7Ca0v08JAN8JyyqNBD+yasao9SH8iy7QoWeAoV3otu8Mony+Jrf02pvLm8b+Z2fZ3zkWbnnzAqO1Wl2+qwufvMvQUY5PGp+COiiKitlUTVfDUj8CksUyK2g=
  file: Gerbers/MNT-113_gerbers.zip
  on:
    repo: w4xzr/MNT-113
  skip_cleanup: 'true'
